# Travis doesn't have a fortran build config, so we'll use c as a base
language: c
branches:
  only: master
sudo: required
install:
    - sudo apt-get install gfortran
    - make -f fortran.makefile standalone.f90.out
    - make -f cpp.makefile standalone.cpp.out
script: 
	- ./standalone.f90.out
	- ./standalone.cpp.out
notifications:
  email:
    on_success: change
    on_failure: change
