# Travis doesn't have a fortran build config, so we'll use c as a base
language: c
branches:
  only:
    - master
sudo: required
install:
    - sudo apt-get install gfortran
    - make -f fortran.makefile standalone.f90.out
script: ./standalone.f90.out
notifications:
  email:
    on_success: change
    on_failure: change
