# Travis doesn't have a fortran build config, so we'll use c as a base
language: c
branches:
  only:
    - master
sudo: required
install:
    - sudo apt-get install gfortran
    - make standalone.out
script: ./standalone.out
notifications:
  email:
    on_success: change
    on_failure: change
